name: CI-Test

on:
  push:
    branches: ["flutterflow"]
  pull_request:
    branches: ["flutterflow"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Git user identity
      - name: Set up Git user
        run: |
          git config --global user.email "xpatrykopiela@gmail.com"
          git config --global user.name "opielapatryk"

      - name: Fetch and checkout main
        run: |
          git fetch origin main:main
          git checkout main

      - name: Merge flutterflow into main
        run: |
          git merge flutterflow --allow-unrelated-histories -Xtheirs

      - name: Commit changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Merge flutterflow into main" || echo "No changes to commit"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://$PAT_TOKEN@github.com/opielapatryk/SpeechPromptAI.git
          git push origin main
