name: flutterflow-push-merge-action

on:
  push:
    branches: ["flutterflow"]
  pull_request:
    branches: ["flutterflow"]
  workflow_dispatch:

jobs:

  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: flutterflow

      # Set up Git user identity
      - name: Set up Git user
        run: |
          git config --global user.email "xpatrykopiela@gmail.com"
          git config --global user.name "opielapatryk"

      - name: Fetch and checkout main branch
        run: |
          git fetch origin
          git checkout main
  
      - name: Merge flutterflow into main with conflict resolution
        run: |
          git merge flutterflow --no-ff --allow-unrelated-histories || true
          git ls-files -u | awk '{print $4}' | xargs git checkout --ours
          git add .
          git commit -m "Resolved merge conflicts by favoring flutterflow branch"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
