name: CI

on:
  push:
    branches: ["flutterflow"]
  pull_request:
    branches: ["flutterflow"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Git user identity
      - name: Set up Git user
        run: |
          git config --global user.email "xpatrykopiela@gmail.com"
          git config --global user.name "opielapatryk"

      - name: Fetch and checkout main
        run: |
          git fetch origin main:main
          git checkout main

      - name: Merge flutterflow into main
        run: |
          git merge flutterflow --allow-unrelated-histories -Xtheirs

      - name: Replace metadata
        run: |
          sed -i 's|<meta property="og:description" content="Built with FlutterFlow." />|<meta property="og:description" content="AiComm-Services" />|g' web/index.html
          sed -i 's|<meta name="twitter:description" content="Built with FlutterFlow." />|<meta name="twitter:description" content="AiComm-Services." />|g' web/index.html
          sed -i 's|<meta property="og:image" content="https://storage.googleapis.com/flutterflow-prod-hosting/og_splash_gradient.png" />|<meta property="og:image" content="https://storage.googleapis.com/aicomm-insp.appspot.com/assets/images/logo-aicomm.png" />|g' web/index.html
          sed -i 's|<meta name="twitter:image" content="https://storage.googleapis.com/flutterflow-prod-hosting/og_splash_gradient.png" />|<meta name="twitter:image" content="https://storage.googleapis.com/aicomm-insp.appspot.com/assets/images/logo-aicomm.png" />|g' web/index.html

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update metadata" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/opielapatryk/SpeechPromptAI.git main

      # Trigger the main branch workflow
      - name: Trigger main branch workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger-main-workflow"}'
