name: CI

on:
  push:
    branches: ["flutterflow"]
  pull_request:
    branches: ["flutterflow"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Git user identity
      - name: Set up Git user
        run: |
          git config --global user.email "xpatrykopiela@gmail.com"
          git config --global user.name "opielapatryk"

      - name: Fetch and checkout main
        run: |
          git fetch origin main:main
          git checkout main

      - name: Merge flutterflow into main
        run: |
          git merge flutterflow --allow-unrelated-histories -Xtheirs

      # Trigger the main branch workflow
      - name: Trigger main branch workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger-main-workflow"}'
